[build]
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn india_agri_platform.api.main:app --host 0.0.0.0 --port ${PORT}"
restartPolicyMaxRetries = 10

[[volumes]]
local_path = "models"
remote_path = "models"
mount_path = "/app/models"

[[volumes]]
local_path = "india_agri_platform"
remote_path = "india_agri_platform"
mount_path = "/app/india_agri_platform"
