[build]
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn india_agri_platform.api.main:app --host 0.0.0.0"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300

# Volume mounts for model persistence (commented out - Railway handles this)
# [[volumes]]
# local_path = "models"
# remote_path = "models"
# mount_path = "/app/models"
