platform:
  name: "India Agricultural Intelligence Platform"
  version: "1.0.0"
  description: "Multi-crop, multi-state agricultural yield prediction and management platform"

  # Supported crops and states
  supported_crops:
    - wheat
    - rice
    - cotton
    - maize

  supported_states:
    - punjab
    - haryana
    - delhi
    - uttar_pradesh
    - bihar
    - madhya_pradesh
    - jharkhand
    - rajasthan
    - maharashtra
    - karnataka
    - tamil_nadu
    - andhra_pradesh

  # Default settings
  default_crop: "wheat"
  default_state: "punjab"

  # Model settings
  model_settings:
    default_algorithm: "random_forest"
    cross_validation_folds: 5
    test_size: 0.2
    random_state: 42

  # Data settings
  data_settings:
    max_cache_age_days: 7
    batch_size: 1000
    parallel_processing: true
    max_workers: 4

  # API settings
  api_settings:
    host: "0.0.0.0"
    port: 8000
    debug: true
    cors_origins: ["*"]

  # External APIs
  external_apis:
    openweather:
      enabled: false
      api_key: ""
      base_url: "https://api.openweathermap.org/data/2.5"
    google_earth_engine:
      enabled: false
      service_account: ""
      project_id: ""
    government_data:
      enabled: true
      base_urls:
        punjab: "https://agri.punjab.gov.in"
        haryana: "https://agri.haryana.gov.in"
        up: "https://upagriculture.com"

  # Feature engineering
  feature_engineering:
    temporal_features: true
    spatial_features: true
    weather_features: true
    soil_features: true
    vegetation_indices: true
    irrigation_features: true
    variety_features: true

  # Performance monitoring
  monitoring:
    enable_metrics: true
    log_predictions: true
    track_model_performance: true
    alert_on_drift: true

  # Security settings
  security:
    api_rate_limiting: true
    max_requests_per_minute: 60
    authentication_required: false
    data_encryption: true
